---
title: "Web Scraping da Plataforma Sucupira dos Trabalhos de Conclusão Pós-Graduação"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Preenchendo formulário:

- Anos: **2017 a 2020**;
- Instituição de Ensino Superior: **UNIVERSIDADE FEDERAL DA BAHIA (UFBA)**;
- Programa: **Ciência da Computação (28001010095P3)**. 

```{r}
library(RSelenium)
```

```{r}
url = 'https://sucupira.capes.gov.br/sucupira/public/consultas/coleta/trabalhoConclusao/listaTrabalhoConclusao.xhtml'
```

```{r}
# start a chrome browser
rD = rsDriver(browser = "chrome", port = 4444L, geckover = NULL, 
               chromever =  "85.0.4183.83", iedrver = NULL, phantomver = NULL)
```

```{r}
remDr = rD$client 
remDr$navigate(url)
```

```{r}
source('web-scraping-rselenium.R')
```

```{r}
#Funcao gera.dataset implementada no arquivo web-scraping-rselenium.R
dados.pgcomp.chrome = gera.dataset()
```

## Tables HTML convertidas em um único data.frame resultante das consultas realizadas:

```{r}
knitr::kable(head(dados.pgcomp.chrome))
```

```{r}
# stop the selenium server
rD$server$stop()
```

